services:
  - type: web
    name: java-project
    env: docker
    plan: free
    dockerfilePath: app/Dockerfile
    envVars:
      - key: PORT
        value: 7070
      - key: JDBC_DATABASE_URL
        value: postgres://project_db_2ary_user:password@dpg-cpk3eemd3nmc73fnvphg-a.oregon-postgres.render.com/project_db_2ary
