name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21

    - name: Build with Gradle
      run: ./gradlew build

    - name: Test with Gradle
      run: ./gradlew test

    - name: Generate test coverage report
      run: ./gradlew jacocoTestReport

    - name: Upload test coverage report
      uses: actions/upload-artifact@v2
      with:
        name: test-coverage-report
        path: build/reports/jacoco/test/html

