name: hexlet-check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.2'

      - name: Build with Gradle
        working-directory: ./app
        run: gradle build

      - name: Test with Gradle
        working-directory: ./app
        run: gradle test

      - name: Generate coverage report
        working-directory: ./app
        run: gradle jacocoTestReport

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html
